export const testTracks = [
{name: 'Shine On You Crazy Diamond Pt. I-V', artist: 'Pink Floyd', album: 'Wish You Were Here', id: 1},
{name: 'Have a Cigar', artist: 'Pink Floyd', album: 'Wish You Were Here', id: 2},
{name: 'Welcome to the Machine', artist: 'Pink Floyd', album: 'Wish You Were Here', id: 3},
{name: 'Wish You Were Here', artist: 'Pink Floyd', album: 'Wish You Were Here', id: 4},
{name: 'Shine On you Crazy Diamond Pt. VI-IX', artist: 'Pink Floyd', album: 'Wish You Were Here', id: 5},
{name: 'Breathe (in the Air)', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 6},
{name: 'On the Run', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 7},
{name: 'Time', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 8},
{name: 'The Great Gig in the Sky', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 9},
{name: 'Money', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 10},
{name: 'Us and Them', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 11},
{name: 'Any the Color you Like', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 12},
{name: 'Brain Damage', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 13},
{name: 'Eclipse', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 14},
{name: 'The Great Gig in the Sky', artist: 'Pink Floyd', album: 'Dark Side of the Moon', id: 15},
]